#!/usr/bin/env python
import ConfigParser
from bzrlib.osutils import dirname
from dircache import listdir
import sys
import os

def main():
    argc = len(sys.argv)
    allowed_options = ['logfile', 'pidfile', 'config_file']
    servers = {}

    def usage():
        print('Usage: %s start|stop|restart' % sys.argv[0])

    if argc > 2:
        server = sys.argv[1]
        action = sys.argv[2]
    elif argc == 2:
        action = sys.argv[1]
    else:
        usage()
        exit(1)

    config_dir = os.path.join(os.path.abspath(dirname(dirname(__file__))), 'teeworlds-server.d')

    if not os.path.exists(config_dir):
        print('%s does not exist.' % config_dir)
        exit(10)

    if not os.access(config_dir, os.R_OK):
        print('%s is not available for reading.' % config_dir)
        exit(11)

    #Reading servers configuration files
    for filename in listdir(config_dir):
        if not filename.endswith('.ini'):
            continue

        filepath = '%s%s%s' % (config_dir, os.path.sep, filename)

        #Reading config file
        config = ConfigParser.ConfigParser()
        config.read(filepath)
        server_section = config.sections()

        #Setting server settings based on supplied parameters
        for server in server_section:
            options = config.options(server)

            for option in options:
                if option in allowed_options:
                    servers.setdefault(server, {})[option] = str(config.get(server, option)).replace('"', '')

    if action == 'start':
        print 'start'
    elif action == 'stop':
        print 'stop'
    elif action == 'restart':
        print 'restart'
    else:
        usage()

if __name__ == '__main__':
    main()